services:
  postgres:
    container_name: kube_news_db
    image: postgres:12.17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgre_docker_vol:/var/lib/postgresql/data 
    networks:
      - kube_news_net

  kube_news:
      container_name: kube_news
      image: teste/kube-news:${KUBE_NEWS_TAG:-latest} #se essa variável não for definida, será latest
      build:
        context: ./src
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      environment:
        DB_DATABASE: ${POSTGRES_DB}
        DB_USERNAME: ${POSTGRES_USER}
        DB_PASSWORD: ${POSTGRES_PASSWORD}
        DB_HOST: kube_news_db
      networks:
        - kube_news_net
      depends_on:
        - postgres

# Atenção: Volumes e network tem que entrar na mesma identação do services (na raiz)
volumes:
  postgre_docker_vol:

networks:
  kube_news_net:
    driver: bridge