services:
  postgres:
    container_name: kube_news_db
    image: postgres:12.17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: kubenews
      POSTGRES_USER: kubenews
      POSTGRES_PASSWORD: Pg123
    volumes:
      - postgre_docker_vol:/var/lib/postgresql/data 
    networks:
      - kube_news_net

  kube_news:
      container_name: kube_news
      image: rrochati/kube-news:v1
      ports:
        - "8080:8080"
      environment:
        DB_DATABASE: kubenews
        DB_USERNAME: kubenews
        DB_PASSWORD: Pg123
        DB_HOST: kube_news_db
      networks:
        - kube_news_net

volumes:
  postgre_docker_vol:

networks:
  kube_news_net:
    driver: bridge